name = "Haku"
license = "All Rights Reserved"
licenselink = "https://re.karlbaey.top"
description = "卡尔白的纸箱📦"
homepage = "https://"
demosite = ""
tags = ["blog", "responsive", "search", "comments", "tags"]
features = ["hugo-pipes", "pagefind", "giscus", "sodesu", "math", "rss"]
min_version = "0.128.0"

[author]
  name = "Karlbaey"
  homepage = ""
