theme = "Haku"
baseURL = "https://example.org/"
locale = "zh-CN"
title = "Haku Example"
enableRobotsTXT = true
disablePathToLower = true

[taxonomies]
tag = "tags"

[pagination]
pagerSize = 7
path = "page"

[outputs]
home = ["HTML", "RSS"]

[outputFormats.RSS]
baseName = "rss"

[params]
subtitle = "Theme preview"
description = "Example site for the Haku theme"
mainSections = ["posts"]

[params.seo]
defaultImage = "/og-default.png"
logo = "/favicon.png"
favicon = "/favicon.png"

[params.posts]
excerptLength = 60

[params.author]
name = "Haku"

[params.copyright]
enabled = false

[params.comments]
defaultProvider = "sodesu"

[params.comments.sodesu]
enabled = true
serverUrl = "https://wa.karlbaey.top"
turnstileKey = "0x4AAAAAACjZ2i92lseLg6_w"
lang = "zh"
login = "enable"
requiredMeta = ["nick", "mail"]
emoji = []
pageSize = 10
commentSorting = "latest"

[markup]
  [markup.tableOfContents]
  startLevel = 2
  endLevel = 4
  ordered = false
  [markup.goldmark]
    [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
      block = true
      title = true
    [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  noClasses = true
